name: Build

on:
  workflow_call:
  push:
    branches-ignore:
    - 'release-v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19.1"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: go build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: e621-dl-${{ runner.os }}
        path: |
          e621-dl
          e621-dl.exe
